@token= eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW1wbGVVc2VyIiwiaWF0IjoxNzUwNjg1ODAyLCJleHAiOjE3NTA3NzIyMDJ9.9D93qZkf4-CSR1SS_qdd7FNdZIprdAvxYQ71q5DFOtY
@baseUrl = http://localhost:8085

POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{
  "username": "sampleUser",
  "password": "secret1234"
}

### Get All Users
GET {{baseUrl}}/api/v1/users
Accept: application/json
Authorization: Bearer {{token}}


### Get product by ID
GET {{baseUrl}}/api/v1/products/1
Accept: application/json
