### Get all products (paginated)
GET http://localhost:8080/api/v1/products?page=0&size=10
Accept: application/json

### GET request to get all products
@id =1
GET http://localhost:8080/api/v1/products/{{id}}
Accept: application/json

### GET request to get all products
@category = Processor
GET http://localhost:8080/api/v1/products/category/{{category}}
Accept: application/json


### Post request to Register Product
POST http://localhost:8080/api/v1/products
Content-Type: application/json
Accept: application/json

{
  "name": "AAANeuraX AI Processor",
  "brand": "NeuraTech",
  "category": "Processor",
  "specifications": "Cores: 64, Clock Speed: 3.2GHz, AI Boost Engine v2",
  "price": 1799.00,
  "imageUrl": "https://example.com/images/neurax.jpg",
  "availability": true
}