spring:
  application:
    name: mankind-gateway-service

  cloud:
    gateway:
      forwarded:
        enabled: false
      discovery:
        locator:
          enabled: false

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin,RETAIN_UNIQUE
        - DedupeResponseHeader=Access-Control-Allow-Credentials,RETAIN_UNIQUE

      routes:
        # Explicit route for /api/v1/cart (no trailing slash)
        - id: cart-root
          uri: ${CART_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/cart
          filters:
            - SetPath=/cart
        # API routes
        - id: user-profile-root
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/me
          filters:
            - RewritePath=/api/v1/users/me, /users/me

        - id: auth
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/auth/(?<segment>.*), /auth/${segment}

        - id: user-profile
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/me/**
          filters:
            - RewritePath=/api/v1/users/me/(?<segment>.*), /users/me/${segment}

        - id: users-admin
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RewritePath=/api/v1/users/(?<segment>.*), /users/${segment}
          
        - id: products
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8080}
          predicates:
            - Path=/api/v1/products/**
          filters:
            - RewritePath=/api/v1/products/(?<segment>.*), /${segment}
          
        - id: cart
          uri: ${CART_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/v1/cart/**
          filters:
            - RewritePath=/api/v1/cart/(?<segment>.*), /cart/${segment}
          
        # Explicit route for /api/v1/coupons (no trailing slash)
        - id: coupons-root
          uri: ${COUPON_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/v1/coupons
          filters:
            - SetPath=/coupons
          
        - id: coupons
          uri: ${COUPON_SERVICE_URL:http://localhost:8087}
          predicates:
            - Path=/api/v1/coupons/**
          filters:
            - RewritePath=/api/v1/coupons/(?<segment>.*), /coupons/${segment}
          
        - id: wishlist
          uri: ${WISHLIST_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/v1/wishlist/**
          filters:
            - RewritePath=/api/v1/wishlist/(?<segment>.*), /wishlist/${segment}

        - id: payments
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/v1/payments/**, /api/v1/admin/payments/**
          filters:
            - RewritePath=/api/v1/payments/(?<segment>.*), /payments/${segment}
            - RewritePath=/api/v1/admin/payments/(?<segment>.*), /admin/payments/${segment}

        - id: notifications
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8086}
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - RewritePath=/api/v1/notifications/(?<segment>.*), /notifications/${segment}

        # Order service routes - admin routes first (more specific)
        - id: admin-orders
          uri: ${ORDER_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/v1/admin/orders/**
          filters:
            - StripPrefix=3
            
        - id: orders-root
          uri: ${ORDER_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/v1/orders
          filters:
            - SetPath=/orders
          
        - id: orders
          uri: ${ORDER_SERVICE_URL:http://localhost:8088}
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - RewritePath=/api/v1/orders/(?<segment>.*), /orders/${segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/mankind
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/mankind/protocol/openid-connect/certs

server:
  port: 8085

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/

resilience4j:
  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1m
        timeout-duration: 0
    instances:
      apiGateway:
        base-config: default
