server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?connectTimeout=${DB_CONNECT_TIMEOUT:60000}&socketTimeout=${DB_SOCKET_TIMEOUT:60000}&useSSL=${DB_USE_SSL:false}&allowPublicKeyRetrieval=${DB_ALLOW_PUBLIC_KEY_RETRIEVAL:true}&serverTimezone=${DB_SERVER_TIMEZONE:UTC}&autoReconnect=${DB_AUTO_RECONNECT:true}&failOverReadOnly=${DB_FAIL_OVER_READ_ONLY:false}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: ${DB_HIKARI_CONNECTION_TIMEOUT:20000}
      maximum-pool-size: ${DB_HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${DB_HIKARI_MIN_IDLE:2}
      idle-timeout: ${DB_HIKARI_IDLE_TIMEOUT:120000}
      max-lifetime: ${DB_HIKARI_MAX_LIFETIME:300000}
      leak-detection-threshold: ${DB_HIKARI_LEAK_DETECTION_THRESHOLD:30000}
      connection-test-query: SELECT 1
      validation-timeout: 5000
      auto-commit: true
      allow-pool-suspension: false
      register-mbeans: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/mankind
          jwk-set-uri: ${KEYCLOAK_URL}/realms/mankind/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: false
        format_sql: false
        current_session_context_class: thread
        transaction:
          auto_commit: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

# Service URLs for Feign clients (will be overridden by environment variables in docker-compose)
USER_SERVICE_URL: ${USER_SERVICE_URL:http://mankind-user-service:8080}
CART_SERVICE_URL: ${CART_SERVICE_URL:http://mankind-cart-service:8080}
COUPON_SERVICE_URL: ${COUPON_SERVICE_URL:http://mankind-coupon-service:8080}
PRODUCT_SERVICE_URL: ${PRODUCT_SERVICE_URL:http://mankind-product-service:8080}

# Production logging configuration
logging:
  level:
    root: WARN
    com.mankind: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
