##replace Token value after each login
@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW1wbGVVc2VyIiwiaWF0IjoxNzQ3MDU4NDY0LCJleHAiOjE3NDcxNDQ4NjR9.5w8X3eDOWTVc_N9kDMCFASjhqwJTrw0C8aCMh0PwG2c
### Create User

POST http://localhost:8081/api/v1/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "sampleUser",
  "email": "sampleUser@email.com",
  "firstName": "sampleUser",
  "lastName": "SomeoneElse",
  "password": "secret1234",
  "role": "USER",
  "active": true
}

### Login
## get auth token

POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "username": "sampleUser",
  "password": "secret1234"
}


###

### Get User by ID
GET http://localhost:8081/api/v1/users/1
Accept: application/json
Authorization: Bearer {{token}}

###

### Get All Users
GET http://localhost:8081/api/v1/users
Accept: application/json
Authorization: Bearer {{token}}


###

### Update User
PUT http://localhost:8081/api/v1/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "firstName": "UpdatedFirstName",
  "lastName": "UpdatedLastName",
  "email": "updated.email@example.com"
}

### Test Update User with Invalid Fields (should be ignored)
PUT http://localhost:8081/api/v1/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzYW1wbGVVc2VyIiwiaWF0IjoxNzQ3MTkxNTM4LCJleHAiOjE3NDcyNzc5Mzh9.U3EKjp9Y6H4cE2kv_SWXi8_vVffwn1apKqYHw-fJNRE

{
  "firstName": "Arjun",
  "lastName": "Sura",
  "email": "arjun.email@example.com",
  "profilePictureUrl": "N/A"

}
