###
# ➕ Add Item to Wishlist (Valid)
POST http://localhost:8082/api/wishlist?userId=1&productId=100
Accept: application/json

###

# ❌ Add Duplicate Item (Triggers DuplicateWishlistItemException)
POST http://localhost:8082/api/wishlist?userId=1&productId=100
Accept: application/json

###

#  Get Wishlist for Existing User
GET http://localhost:8082/api/wishlist/1
Accept: application/json

###

# ❌ Get Wishlist for Non-Existing User or Empty Wishlist (Triggers UserNotFoundException)
GET http://localhost:8082/api/wishlist/999
Accept: application/json

###

# ❌ Delete Item Not in Wishlist (Triggers RuntimeException)
DELETE http://localhost:8082/api/wishlist?userId=1&productId=899
Accept: application/json

###

# 🗑️ Delete Valid Item from Wishlist
DELETE http://localhost:8082/api/wishlist?userId=1&productId=100
Accept: application/json
